# To learn about this file, please see https://www.gitpod.io/docs/references/gitpod-yml

image: gitpod/workspace-postgres

tasks:
  - init: |
      # Cleanup terminal
      printf "\033[3J\033c\033[3J"

      # Auto init a redwoodjs project for Gitpod if missing
      if test ! -e redwood.toml; then {
        # Create
        yarn create redwood-app . --overwrite --yarn-install --typescript --git-init=false

        # Custom webpack config for Gitpod
        yarn rw setup webpack
        wp_config_file="web/config/webpack.config.js"
        if ! grep -q "GITPOD_REPO_ROOT" "${wp_config_file}" 2>/dev/null; then {
          sed -i "s|if (mode === 'development') {|& \n\t\tif (process.env.GITPOD_REPO_ROOT) { config.devServer.client.webSocketURL = require('child_process').execSync(\`gp url \${config.devServer.port}\`).toString().trim().replace('https', 'wss').concat('/ws') }|" "${wp_config_file}"
        } fi

        # Change the default `sqlite` datasource provider to `postgres`
        sed -i 's|provider = "sqlite"|provider = "postgres"|' "api/db/schema.prisma"
      } fi

    command: |
      cmd="yarn rw dev"
      printf "Executing '%s' ..." "${cmd}"
      ${cmd}

ports:
  - port: 5432
    name: PostgreSQL database
    onOpen: ignore
  - port: 8910
    name: RedwoodJS web application
    onOpen: notify # because we already have [browser].open = true in redwood.toml
  - port: 8911
    name: Serverless functions
    onOpen: ignore

vscode:
  extensions:
    - "dbaeumer.vscode-eslint"
    - "eamodio.gitlens"
    # - "ofhumanbondage.react-proptypes-intellisense" - Not published to Open VSX (yet)
    - "mgmcdermott.vscode-language-babel"
    - "wix.vscode-import-cost"
    - "pflannery.vscode-versionlens"
    - "editorconfig.editorconfig"
    - "prisma.prisma"
    - "graphql.vscode-graphql"
